<?php

// This is where all the API connect scripts will go to make it easier to read

function newCustomPost($custom_title, $content) {

    // All the globals are found in env.php which is in .gitignore so ask me for the codes otherwise this won't work, codes are on need to know basis to reduce risk - hope you understand
    global $wp_bearer;
    
    $post_data = [
        "title" => $custom_title,
        "content" => $content,
        "excerpt" => "This is some short text",
        "status" => "publish"
    ];
    

    $ch = curl_init();
    
    curl_setopt($ch, CURLOPT_URL, 'https://staging2.conveyancingqld.com/wp-json/wp/v2/for-you');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($post_data));
    
    $headers = array();
    $auth = 'Authorization: Basic '.$wp_bearer;
    $headers[] = $auth;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    
    //$id = $result['id'];
    //$json_result = json_decode($result);
    //return $json_result['link'];
    return $result;
    
}


function getBearImage($uid) {
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

global $bb_bearer;

curl_setopt($ch, CURLOPT_URL, 'https://api.bannerbear.com/v2/images/'.$uid);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$auth = 'Authorization: Bearer '.$bb_bearer;
echo "Header Banner Bear auth are: ".$auth; 
$headers[] = $auth;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$array_result = json_decode($result, true);

echo "The results from banner pull are: ";
var_dump($array_result);



$image_url = $array_result['image_url'];


return $image_url; 

}

function customFieldPush($id, $url_array) { // still need to add custom field values
    global $wp_bearer;
    $url = http_build_query($url_array);
    $ch = curl_init();
    
    curl_setopt($ch, CURLOPT_URL, 'https://staging2.conveyancingqld.com/wp-json/acf/v3/for-you/'.$id);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $url);
    
    $headers = array();
    $auth = 'Authorization: Basic '.$wp_bearer;
    $headers[] = 'Authorization: Basic d2h5d29udHlvdWNvbm5lY3Q6Y2N1WSAxWWhkIDdsTmkgMzdWSSB5MVlyIDYySEs=';
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    
    
    
    
    
}

function SMS_Voyage($text) {

    global $voyage_secret;

    $ch = curl_init();
    
    $sms_data = [
        "from" => 'PHP Robot',
        "text" => 'Yes this is really coming from code',
        "to" => "61412826569",
        "api_key" => "d3e293a6",
        "api_secret" => $voyage_secret
        
    ];
    
    
    
    curl_setopt($ch, CURLOPT_URL, 'https://rest.nexmo.com/sms/json');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($sms_data));
    
    $headers = array();
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    
    
    }

function short_It($url, $path) {

    global $shortio_secret;

    $ch = curl_init();
    
    $short_data = [
        "allowDuplicates" => true,
        "domain" => '4a4y.short.gy',
        "originalURL" => $url,
        "path" => $path,
        "title" => "PHP Campaign [You Have Arrived]",
    ];
    
    curl_setopt($ch, CURLOPT_URL, 'https://api.short.io/links');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($short_data));
    
    $headers = array();
    $headers[] = 'Accept: application/json';
    $auth = 'Authorization: '.$shortio_secret;
    $headers[] = $auth;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    
    $array_result = json_decode($result, true);
    return $array_result;
    
    }

    function OGLinkStatus($link_id, $title, $description, $image) {

        global $shortio_secret;

        $ch = curl_init();

        
        
        $post_url = 'https://api.short.io/links/opengraph/415022/'.$link_id;

        
        
        curl_setopt($ch, CURLOPT_URL, $post_url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
        
        curl_setopt($ch, CURLOPT_POSTFIELDS, "[[ \"title\" , \"".$title."\" ], [ \"description\" , \"".$description."\" ], [ \"image\" , \"".$image."\" ], [\"image:type\" , \"image/png\" ]]");
        
        $headers = array();
        $auth = 'Authorization: '.$shortio_secret;
        $headers[] = $auth;
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        
        
        
        }


    // This function creates a Banner for a test OG image 
    function bannerCreate($name) {

        global $bb_bearer;

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        
        curl_setopt($ch, CURLOPT_URL, 'https://api.bannerbear.com/v2/images?=');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"template\": \"RnxGpW5lpEn5EXrJ1Y\",\n  \"modifications\": [\n    {\n      \"name\": \"image_container\",\n      \"image_url\": \"https://i.ibb.co/4fZ5fmD/presenter.png\"\n    },\n    {\n      \"name\": \"rectangle_background\",\n      \"color\": null\n    },\n    {\n      \"name\": \"rectangle_border\",\n      \"color\": null\n    },\n    {\n      \"name\": \"title\",\n      \"text\": \"Hi *".$name."* ut consectetur ligula, eu pulvinar dolor. In ornare fringilla ullamcorper. Donec et fringilla lorem. Sed ornare porttitor maximus.\",\n      \"color\": null,\n      \"background\": null\n    },\n    {\n      \"name\": \"subtitle_1\",\n      \"text\": \"Lorem ipsum\",\n      \"color\": null,\n      \"background\": null\n    },\n    {\n      \"name\": \"subtitle_2\",\n      \"text\": \"Nullam viverra\",\n      \"color\": null,\n      \"background\": null\n    },\n    {\n      \"name\": \"footer\",\n      \"text\": \"Lorem ipsum\",\n      \"color\": null,\n      \"background\": null\n    },\n    {\n      \"name\": \"svg_icon\",\n      \"color\": null,\n      \"border_color\": null,\n      \"border_width\": null\n    }\n  ],\n  \"webhook_url\": null,\n  \"transparent\": false,\n  \"metadata\": null\n}\n\n");
        
        $headers = array();
        $auth = 'Authorization: '.$bb_bearer;
        $headers[] = $auth;
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        $result_decode = json_decode($result, true);
        $uid = $result_decode['uid'];
        
        return $uid;
        }

        // For now - creating a test Synthesia video for proof of concept - pass the returning ID to Wordpress custom field 
        function robotUprising($name) {
            $ch = curl_init();
            
            //var_dump ($post_data);
            $json = json_encode($post_data);
            echo $json;
            
            curl_setopt($ch, CURLOPT_URL, 'https://api.synthesia.io/v2/videos');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, '{ "test": true, "title": "Hello, World!", "description": "This is my first synthetic video, made with the Synthesia API!", "visibility": "public", "input": [ { "scriptText": "Welcome '.$name.', to the real world.", "avatar": "anna_costume1_cameraA", "avatarSettings": { "voice": "1364e02b-bdae-4d39-bc2d-6c4a34814968", "style": "rectangular" },  "background": "off_white" } ] }');
            
            $headers = array();
            $headers[] = 'Authorization: 326833a9a47aae3809b06ac4e5049d98';
            $headers[] = 'Content-Type: application/json';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            
            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);
            echo "Synthesia return is: ";
            var_dump($result);
            $array_result = json_decode($result, true);
            return $array_result['id'];
            
            }

/*


// Create Banner

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.bannerbear.com/v2/images');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"template\": \"A37YJe5qYyY5mpvWKP\",\n  \"modifications\": [\n    {\n      \"name\": \"avatar\",\n      \"image_url\": \"https://cdn.bannerbear.com/sample_images/welcome_bear_photo.jpg\"\n    },\n    {\n      \"name\": \"name\",\n      \"text\": \"Where is your mind\",\n      \"color\": null,\n      \"background\": null\n    },\n    {\n      \"name\": \"handle\",\n      \"text\": \"Something special\",\n      \"color\": null,\n      \"background\": null\n    },\n    {\n      \"name\": \"tweet\",\n      \"text\": \"Specialist handle\",\n      \"color\": null,\n      \"background\": null\n    }\n  ],\n  \"webhook_url\": null,\n  \"transparent\": false,\n  \"metadata\": null\n}");

$headers = array();
$headers[] = 'Authorization: Bearer bb_pr_e86cde3c8f925d114048c654ed3f06';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$image = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$image_id = $image['uid'];

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.bannerbear.com/v2/images/'.$image['uid']);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Authorization: Bearer bb_pr_e86cde3c8f925d114048c654ed3f06';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$image_url = $result['image_url'];

*/



/*
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

// Need to convert URL  to this: https%3A%2F%2Fconveyancingqld.com%2Fyour-referral-offer%2F&name=your-offer

curl_setopt($ch, CURLOPT_URL, 'https://cutt.ly/api/api.php?key=dd4e6982afb771ded9cd25ead2499b1ce6f47&short='.$url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$short_link = $result['url']['shortLink'];  


*/


/*


*/
